import { SignIn } from './Sign-In/Sign-in'
import { SignUp } from './Sign-Up/Sign-up'
import { Home } from './Home/Home'
import { HomePage } from './HomePage/HomePage'
import { NotFound } from './NotFound/NotFound'
import { ProductDetail } from './Product/Product'
import { ShoppingCart } from './Shopping-Cart/ShoppingCart'
import { Favorites } from './Favorites/Favorites'
import { Orders } from './Orders/Orders'
export{SignIn, SignUp, Home, HomePage, NotFound, ProductDetail, ShoppingCart, Favorites, Orders}
